server.port=${PORT:8080}

spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}
consumer.topic=${PAYMENT_PROCESSED_TOPIC:cidev-payment-processed}
consumer.group-id=${PAYMENT_RECONCILIATION_GROUP_NAME:payment-reconciliation-consumer}
consumer.max-attempts=${MAX_ATTEMPTS:5}
consumer.backoff-delay=${BACKOFF_DELAY:1000}
consumer.concurrency=${CONCURRENT_LISTENER_INSTANCES:1}

spring.mongodb.uri=${MONGODB_URL:mongodb://localhost:27017/payment_reconciliation}
                    

spring.mongodb.database=${MONGODB_DATABASE:payment_reconciliation}

management.endpoints.access.default=none
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.access=read_only
management.health.mongodb.enabled=false

payments.api-key=${PAYMENTS_API_KEY:default_api_key}
payments.api-url=${PAYMENTS_API_URL:http://api-payments.chs.local:4001}

skip.gone.resource=${SKIP_GONE_RESOURCE:false}
skip.gone.resource.id=${SKIP_GONE_RESOURCE_ID:}